#!/usr/bin/env sh
#YABAI STUFF

# bsp or float (default: bsp)
#yabai -m config layout bsp

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Authy Desktop$" sticky=on layer=above manage=off
yabai -m rule --add app="^KakaoTalk$" manage=off
yabai -m rule --add app="^Moom$" manage=off
yabai -m rule --add app="^Spotify$" manage=off

# global settings
yabai -m config focus_follows_mouse     off
yabai -m config mouse_follows_focus     on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement        second_child
yabai -m config window_topmost          off
yabai -m config window_shadow           float
yabai -m config window_opacity          off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity   1.0

# some other settings
yabai -m config auto_balance            off
yabai -m config split_ratio             0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier          ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2           resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1           move


## Change how yabai looks
yabai -m config layout                  bsp
yabai -m config top_padding             2
yabai -m config bottom_padding          2
yabai -m config left_padding            2
yabai -m config right_padding           2
yabai -m config window_gap              10

# WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
yabai -m config window_border           off

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight &>/dev/null &

